export const EDIT_PHRASE = "EDIT_PHRASE";
export const ADD_PHRAZE = "ADD_PHRAZE";
export const CHECK_BOX_PHRAZE = "CHECK_BOX_PHRAZE";
export const DELETE_PHRAZE = "DELETE_PHRAZE";
export const GET_PHRAZES_BY_CATEGORY = 'GET_PHRAZES_BY_CATEGORY'
